import { firebaseConfig } from './firebase-config.js';
const configured=!Object.values(firebaseConfig).some(v=>String(v).startsWith('PASTE_'));
const $=id=>document.getElementById(id),modal=$('cloudModal'),btn=$('cloudBtn'),info=$('cloudInfo'),text=$('syncText'),dot=$('syncDot');
const mobileLogin=()=>matchMedia('(max-width:760px)').matches||matchMedia('(display-mode:standalone)').matches;
let auth=null,db=null,user=null,unsub=null,suppress=false,timer=null;
function status(label,color='#22c55e'){text.textContent=label;dot.style.background=color}
if(!btn||!modal)throw new Error('Cloud login interface is missing');btn.onclick=()=>modal.style.display='grid';$('closeCloud').onclick=()=>modal.style.display='none';
if(!configured){status('雲端同步：未設定','#f59e0b');info.innerHTML='尚未填入 Firebase 設定。請先完成 firebase-config.js，再把 GitHub Pages 網域加入 Firebase Authentication 的 Authorized domains。';['googleLogin','googleLogout','uploadCloud','downloadCloud'].forEach(id=>{const el=$(id);if(el)el.disabled=true});}
async function start(){if(!configured)return;try{const appmod=await import('https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js');const authmod=await import('https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js');const fsmod=await import('https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js');const app=appmod.initializeApp(firebaseConfig);auth=authmod.getAuth(app);db=fsmod.getFirestore(app);window.FB={...authmod,...fsmod};authmod.onAuthStateChanged(auth,async u=>{user=u;if(!u){status('雲端同步：未登入','#f59e0b');btn.textContent='雲端登入';if(unsub)unsub();return}btn.textContent='雲端已啟用';status('正在同步...','#3b82f6');const ref=fsmod.doc(db,'users',u.uid,'portfolio','main');unsub=fsmod.onSnapshot(ref,snap=>{if(snap.exists()){suppress=true;window.ETFProApp.setState(snap.data().state||{});suppress=false;status('雲端同步：已啟用','#22c55e');info.textContent='Google帳戶：'+(u.email||'已登入')+'｜資料已同步';}else status('雲端已啟用，等待首次上載','#f59e0b')},()=>status('同步失敗，請重試','#ef4444'));});
$('googleLogin').onclick=async()=>{try{const provider=new authmod.GoogleAuthProvider();if(mobileLogin())await authmod.signInWithRedirect(auth,provider);else await authmod.signInWithPopup(auth,provider)}catch(e){const msg=e.code==='auth/cancelled-popup-request'?'登入程序已取消，請關閉其他登入視窗後再試。':e.code==='auth/popup-blocked'?'瀏覽器已封鎖登入視窗，手機版會改用重新導向登入。':e.code==='auth/popup-closed-by-user'?'登入視窗已關閉，請再按一次登入。':e.message;info.textContent=msg;status('登入失敗','#ef4444')}};$('googleLogout').onclick=()=>authmod.signOut(auth);$('uploadCloud').onclick=()=>user?writeCloud():status('請先登入 Google','#f59e0b');$('downloadCloud').onclick=async()=>{if(!user){status('請先登入 Google','#f59e0b');return;}const snap=await fsmod.getDoc(fsmod.doc(db,'users',user.uid,'portfolio','main'));if(snap.exists())window.ETFProApp.setState(snap.data().state||{});};window.addEventListener('etf-local-save',e=>{if(suppress||!user)return;clearTimeout(timer);status('正在同步...','#3b82f6');timer=setTimeout(()=>writeCloud(e.detail),600)});async function writeCloud(s=window.ETFProApp.getState()){if(!user)return;await fsmod.setDoc(fsmod.doc(db,'users',user.uid,'portfolio','main'),{state:s,updatedAt:fsmod.serverTimestamp()},{merge:true});status('雲端同步：已啟用','#22c55e')}}catch(e){status('Firebase載入失敗','#ef4444');info.textContent=e.message}}
start();window.addEventListener('online',()=>user&&status('正在重新連線...','#3b82f6'));window.addEventListener('offline',()=>status('離線模式','#f59e0b'));
