import { firebaseConfig } from './firebase-config.js';
const $=id=>document.getElementById(id),configured=!Object.values(firebaseConfig).some(v=>!v||String(v).startsWith('PASTE_')||String(v).startsWith('REPLACE_'));
const modal=$('cloudModal'),cloudButton=$('cloudBtn'),info=$('cloudInfo'),syncText=$('syncText'),syncDot=$('syncDot'),googleLogin=$('googleLogin'),uploadCloud=$('uploadCloud'),downloadCloud=$('downloadCloud'),googleLogout=$('googleLogout');
let auth=null,db=null,fs=null,currentUser=null,timer=null,inFlight=false,pending=null,applying=false,pulledUid='';
const ALLOWED=['trades','prices','hkdCash','usdCash','nextPay','currentFx','theme','lastSaved','lastPriceUpdate','marketDate','ranges','editIndex','marketRefQ','marketRefV','snapshots','targets','mainBuy','monthlyBudgets','strategyHistory','lastBackup','monthlyCompleted','dividends','goals','audit','lastCloudSync','cashLedger','cashTransactions','v49ExchangeMigrated'];
function status(m,k='idle'){if(syncText)syncText.textContent=m;if(info)info.textContent=m;if(syncDot)syncDot.style.background=k==='ok'?'#22c55e':k==='error'?'#ef4444':k==='busy'?'#3b82f6':'#f59e0b'}
function controls(user){const signed=Boolean(user);if(googleLogin)googleLogin.style.display=signed?'none':'';[uploadCloud,downloadCloud].forEach(x=>{if(x)x.style.display=signed?'':'none'});if(googleLogout)googleLogout.style.display=signed?'':'none'}
function cleanRemote(raw){const clean={};if(!raw||typeof raw!=='object')return clean;for(const key of ALLOWED)if(Object.prototype.hasOwnProperty.call(raw,key))clean[key]=raw[key];return clean}
function local(){return window.ETFProApp?.getState?.()||{}}
function time(v){const x=Date.parse(v||'');return Number.isFinite(x)?x:0}
function remoteTime(s){const d=s.data()||{};return d.updatedAt?.toMillis?.()||time(d.clientUpdatedAt||d.state?.lastSaved)}
function ref(u){return fs.doc(db,'users',u.uid,'portfolio','main')}
function wait(p,ms=15000){let t;return Promise.race([p,new Promise((_,r)=>t=setTimeout(()=>r(Error('同步逾時')),ms))]).finally(()=>clearTimeout(t))}
function apply(raw){const clean=cleanRemote(raw);localStorage.setItem('ETF_CORE_PRO_V1_PRE_AUTO_CLOUD_DOWNLOAD',JSON.stringify(local()));applying=true;try{window.ETFProApp.setState(clean)}finally{applying=false}}
async function push(data){if(!currentUser||!data)return;pending=data;if(inFlight)return;inFlight=true;try{while(pending&&currentUser){const next=pending;pending=null;status('同步狀態：背景同步中','busy');await wait(fs.setDoc(ref(currentUser),{state:next,clientUpdatedAt:next.lastSaved||new Date().toISOString(),updatedAt:fs.serverTimestamp()},{merge:true}));status('同步狀態：🟢 已與雲端同步','ok')}}catch(e){pending=pending||data;status(`同步失敗：${e.message}`,'error')}finally{inFlight=false}}
function schedule(data){if(!currentUser||applying||!data)return;pending=data;clearTimeout(timer);status('同步狀態：🟡 等候上載');timer=setTimeout(()=>push(pending),900)}
async function pull(u){if(!u||pulledUid===u.uid)return;pulledUid=u.uid;status('同步狀態：正在比較資料','busy');try{const snap=await wait(fs.getDoc(ref(u)));if(!snap.exists())return push(local());const remote=snap.data()?.state,rt=remoteTime(snap),lt=time(local().lastSaved);if(remote&&rt>lt)apply(remote);else if(lt>rt)await push(local());status('同步狀態：🟢 已與雲端同步','ok')}catch(e){pulledUid='';status(`啟動同步失敗：${e.message}`,'error')}}
function authUI(user){currentUser=user||null;controls(currentUser);if(!currentUser){pulledUid='';if(cloudButton)cloudButton.textContent='雲端登入';return status('同步狀態：尚未登入')}if(cloudButton)cloudButton.textContent='已登入';status('同步狀態：已登入','ok');void pull(currentUser)}
controls(null);cloudButton?.addEventListener('click',()=>{if(modal)modal.style.display='grid'});$('closeCloud')?.addEventListener('click',()=>{if(modal)modal.style.display='none'});window.addEventListener('etf-local-save',e=>schedule(e.detail));
async function start(){if(!configured)return status('Firebase尚未設定','error');try{const appmod=await import('https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js'),authmod=await import('https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js');fs=await import('https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js');const app=appmod.initializeApp(firebaseConfig);auth=authmod.getAuth(app);db=fs.getFirestore(app);await authmod.setPersistence(auth,authmod.browserLocalPersistence);authmod.onAuthStateChanged(auth,authUI);googleLogin.onclick=()=>{const popup=authmod.signInWithPopup(auth,new authmod.GoogleAuthProvider());status('正在開啟Google登入','busy');popup.catch(e=>status(`登入失敗：${e.message}`,'error'))};googleLogout.onclick=()=>authmod.signOut(auth);uploadCloud.onclick=()=>push(local());downloadCloud.onclick=()=>{pulledUid='';void pull(currentUser)}}catch(e){status(`Firebase載入失敗：${e.message}`,'error')}}
start();window.addEventListener('online',()=>currentUser&&(pending?void push(pending):(pulledUid='',void pull(currentUser))));window.addEventListener('offline',()=>status('同步狀態：離線，資料保存在本機'));
